plugins {
	id 'fabric-loom' version '1.11.8'
	id 'java'
}

version = "${project.mod_version}+fabric"
group = 'net.geforcemods'
base.archivesName = 'SecurityCraft'

java {
	toolchain.languageVersion = JavaLanguageVersion.of(21)
	withSourcesJar()
}

repositories {
	maven {
		url = 'https://api.modrinth.com/maven'
		content { includeGroup 'maven.modrinth' }
	}
}

loom {
	accessWidenerPath = file('src/main/resources/securitycraft.accesswidener')
	mixin {
		defaultRefmapName = 'securitycraft.refmap.json'
	}
}

sourceSets.main.resources {
	srcDir 'src/generated/resources'
}

dependencies {
	minecraft "com.mojang:minecraft:${project.mc_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	modImplementation "maven.modrinth:forge-config-api-port:${project.forge_config_api_port_version}"
}

processResources {
	inputs.property 'version', project.version
	filesMatching('fabric.mod.json') {
		expand 'version': project.version
	}
	duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release = 21
	options.compilerArgs << '-Xmaxerrs' << '100000'
}

jar {
	from('LICENSE') {
		rename { "${it}_SecurityCraft" }
	}
}
